[book]
authors      = [ "Le Quang Thang" ]
language     = "en"
multilingual = false
src          = ""                                   # Root of repo
title        = "Notes for Terraform Up and Running"

[preprocessor.callouts]
[preprocessor.alerts]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.pagetoc]

[preprocessor.yml-header]

[output.html]
additional-css       = [ "theme/css/catppuccin.css", "theme/pagetoc.css" ]
default-theme        = "latte"
preferred-dark-theme = "macchiato"

smart-punctuation = true

site-url           = "/terraform-up-and-running/"
git-repository-url = "https://github.com/lethang7794/terraform-up-and-running"
edit-url-template  = "https://github.com/lethang7794/terraform-up-and-running/edit/main{path}"

additional-js = [
  "theme/mermaid/mermaid.min.js",
  "theme/mermaid/mermaid-init.js",
  "theme/pagetoc.js",
]
